#!/usr/bin/env bash
CLASSPATH=/usr/share/phoenicis-playonlinux/*:${CLASSPATH}

java -cp "$CLASSPATH":org.phoenicis.javafx.JavaFXApplication --module-path "/usr/share/openjfx/lib/" --add-modules javafx.controls,javafx.web org.phoenicis.javafx.JavaFXApplication
